version: '3.7'

services:
  postgres:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    networks:
      - traefik
  web:
    restart: always
    image: web
    build: ./
    environment:
      - POSTGRES_HOST=postgres
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    #ports:
    #  - "8000:8000" # Not needed since traefik handles the routing
    networks:
      - traefik
    labels:
      - traefik.http.routers.web-router.rule=Host(`taclia.acmotos.com`)
      - traefik.http.routers.web-router.entryPoints=websecure
      - traefik.http.routers.web-router.tls=true

networks:
  traefik:
    external: true
