version: '3.7'

services:
  postgres:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    networks:
      - backend
  web:
    restart: always
    image: web
    build: ./
    environment:
      - DJANGO_SUPERUSER_USERNAME=foo
      - DJANGO_SUPERUSER_EMAIL=foo@example.com
      - DJANGO_SUPERUSER_PASSWORD=bar
      - POSTGRES_HOST=postgres
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py createsuperuser --noinput &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    networks:
      - backend
networks:
    backend: