# Generated by Django 3.0.4 on 2020-03-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_remove_order_purchased_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBookQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_books', to='bookshop.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
