# Generated by Django 3.0.4 on 2020-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_auto_20200324_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Order'), ('PAID', 'Paid')], default='NEW', max_length=32),
        ),
    ]
