# Generated by Django 3.0.4 on 2020-03-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchased_books',
        ),
    ]
