# Generated by Django 3.0.4 on 2020-03-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_auto_20200323_1814'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_genre_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='orderbookquantity',
            constraint=models.UniqueConstraint(fields=('id', 'order', 'book'), name='unique_book_by_order_constraint'),
        ),
    ]
